CREATE DATABASE FindMyBus;

USE FindMyBus;

CREATE TABLE bus(
    bus_no VARCHAR(255) PRIMARY KEY,
    source VARCHAR(255),
    destination VARCHAR(255)
);

INSERT INTO bus (bus_no, source, destination) VALUES
('1', 'RAMNAGAR', 'PALBAZAR'),
('1A', 'RAMNAGAR', 'MUKUNDAPUR'),
('1B', 'RAMNAGAR', 'NAYABAD (GARIA)'),
('3', 'SRERAMPORE', 'SALT LAKE TECHNOPOLIS'),
('3B', 'Milk Colony', 'New Alipore'),
('3C/1', 'Nagerbazar', 'Anandapur'),
('3C/2', 'Nagerbazar', 'Anandapur'),
('3D', 'Milk Colony', 'Sakher Bazar (via Khidirpur)'),
('3D/1', 'Milk Colony', 'Sakher Bazar (via Alipur)'),
('12', 'Rajabagan', 'Rajabazar'),
('12A', 'Rajabagan', 'Howrah Station'),
('12B', 'Kamal Talkies', 'Esplanade'),
('12A­D', 'Akrafatak', 'Howrah Station'),
('12/1', 'Fatepur 28 No', 'Sealdah'),
('12C', 'Pailan', 'Howrah Station'),
('12C/1', 'Shibrampur', 'Howrah Station'),
('12C/1A', 'Konchowki', 'Howrah Station'),
('12C/2', 'Thakdari', 'Howrah Station'),
('13', 'Parnasree', 'Sealdah'),
('13A', 'Shampa Mirza Nagar', 'B.B.D. Bagh'),
('13C', 'Old Dakghar', 'Layalka'),
('17', 'Chetla', 'Howrah Station'),
('17B', 'Baghajatin', 'Howrah Station'),
('18B', 'Dakghar', 'Howrah Station'),
('18B/1', 'Dakghar', 'Ruby/China Mandir'),
('18C', 'Kestor More', 'Anandapur'),
('18D', 'Surya Sen Nagar', 'Howrah Station'),
('21', 'Barisha', 'Sealdah (via Siriti)'),
('21/1', 'Barisha', 'Sealdah (via Taratala)'),
('23', 'Barasat', 'Boalghata'),
('24', 'Topsia', 'Bandhaghat'),
('24A', 'Topsia', 'Bandhaghat'),
('24A/1', 'Mukundapur', 'Howrah Fire Service Station'),
('24B', 'Dhapa', 'Howrah Station'),
('28', 'Howrah Maidan', 'Sealdah'),
('30A', 'Sinthee', 'Esplanade'),
('30B', 'Gouripur', 'Babughat'),
('30B/1', 'Gouripur', 'Howrah Station'),
('30C', 'Hatiara', 'Babughat (via Shyambazar)'),
('30C/1', 'Hatiara', 'Babughat (via Ultadanga)'),
('30D', 'Dum Dum-Cantonment Station', 'Babughat'),
('32', 'Dakshineshwar', 'Esplanade'),
('32A', 'Dakshineshwar', 'Salt Lake Technopolis'),
('34B', 'Dunlop', 'Esplanade'),
('34B/1', 'Pardankuni', 'Esplanade'),
('34C', 'Noapara/Dum Dum-Cantonment (Pramod Nagar)', 'Esplanade'),
('37', 'Dhakuria', 'Howrah Station'),
('37A', 'Nayabad (Garia)', 'Howrah Station'),
('39', 'Picnic Garden', 'High Court'),
('39A/2', 'Howrah Station', 'VIP Bazar'),
('40A', 'Julpia', 'Babughat'),
('40B', 'Thakurpukur', 'Babughat'),
('41', 'Layalka', 'Howrah Station'),
('41B', 'Howrah Station', 'Netaji Nagar'),
('42A', 'Picnic Garden', 'Bichalighat'),
('42B', 'Beliaghata Sales Tax', 'Bichalighat'),
('42C', 'Salt Lake Tank No.13', 'Ruby Hospital'),
('43', 'Dakshineswar', 'Esplanade'),
('43/1', 'Dakshineswar', 'Esplanade'),
('44', 'Baguihati', 'Howrah Station'),
('44A', 'Salt Lake', 'Howrah Station'),
('45', 'Padmashree', 'Airport Gate No.1'),
('45/1', 'Garia Railway Station', 'Beleghata Building More'),
('45A', 'Garia Railway Station', 'Gouripur'),
('45B', 'Garia Railway Station', 'Beleghata Building More'),
('46', 'Airport Gate No.1', 'Esplanade'),
('46B', 'Akansha', 'Esplanade'),
('47', 'Lake Town', 'Unitech via Karunamoyee'),
('47A', 'Lake Town', 'Dhakuria'),
('47B', 'Lake Town (Jaya)', 'Kalikapur (Ruby)'),
('47/1', 'Tollygunge Tram Depot', 'Salt Lake Tank No.12'),
('51', 'Pardankuni', 'Howrah Station'),
('52', 'Ramrajatal', 'Esplanade'),
('54', 'Ballykhal', 'Esplande'),
('54/2', 'Rishra Station', 'Howrah Station'),
('55', 'Botanical Garden', 'Esplanade'),
('55A', 'Shibpur Tram Depot', 'Esplanade'),
('56', 'Howrah Station', 'Ruiya Purbapara'),
('57', 'Kona', 'Esplanade'),
('57A', 'Chanditala', 'Howrah Station'),
('58', 'Chatterjee hat', 'Esplanade'),
('59', 'Bakultala', 'Esplanade'),
('61', 'Alampur', 'Howrah Station'),
('63', 'Domjur', 'Howrah Station'),
('64', 'Uluberia', 'Tulsiberia'),
('68', 'Bagnan', 'Kamalpur'),
('69', 'Sankrail', 'Howrah Station'),
('70', 'Amta', 'Uluberia'),
('71', 'Salt Lake', 'Howrah Maidan (Rare service)'),
('72', 'Dasnagar', 'Park Circus'),
('72A', 'Basirhat', 'Dhamakhali'),
('73', 'Dasnagar', 'Esplanade'),
('75', 'Roypur', 'Babughat'),
('76', 'Amta', 'Bagnan'),
('77', 'Amta', 'Sankrail'),
('77A', 'Batanagar', 'Esplanade'),
('78', 'Barrackpore Court', 'Esplanade'),
('78/1', 'Rahara Bazar/Parthapur', 'Babughat'),
('78C/1', 'Barasat', 'Dakshineshwar'),
('78E', 'Bongaon', 'Dakshineshwar'),
('79', 'Dunlop', 'Panchla'),
('79B', 'Bagbazar', 'Barasat'),
('79D', 'Madhyamgram', 'Babughat'),
('80', 'Chunabhati', 'Howrah Station'),
('80A', 'Garia Bus Stand', 'Esplanade (via Tollygunge)'),
('80B', 'Garia Bus Stand', 'Esplanade (via Jadavpur)'),
('81', 'Barasat', 'Barrackpore Fishery Gate'),
('83', 'Falta', 'Babughat'),
('85', 'Barrackpore Court', 'Kanchrapara'),
('87', 'Barasat', 'Jaguli'),
('87A', 'Barasat', 'Naihati'),
('88', 'Barasat', 'Kanchrapara'),
('91', 'Shyambazar', 'Bhangor / Ghatakpukur'),
('91A', 'Shyambazar', 'Haroa'),
('91B', 'Shyambazar', 'Bhojerhat'),
('91C', 'Shyambazar', 'Lauhati'),
('92', 'Bongaon', 'Boyra'),
('92A', 'Bongaon', 'Duttaphulia'),
('93', 'Bagbazar', 'Kharibari'),
('94', 'Kakdwip Lot 8', 'Namkhana'),
('95', 'Bongaon', 'Ashoknagar'),
('96C', 'Bongaon', 'Duttaphulia'),
('201', 'Nimta', 'Salt Lake Mahisbathan 215A bus Stand'),
('202', 'Nagerbazar', 'Science City'),
('204/1', 'Chetla', 'Rajabazar'),
('205', 'Bansdroni', 'Babughat'),
('205A', 'Bansdroni', 'Babughat'),
('206', 'New Garia Station', 'Salt Lake AJ Block'),
('208', 'Kudghat', 'Howrah Station'),
('210', 'Raichak', 'Esplanade'),
('211', 'Ahiritola', 'Kharibari'),
('211A', 'Ahiritola', 'Langolpota'),
('211B', 'Ahiritola', 'Ganraguri via Karunamoyee'),
('212', 'Palbazar', 'Howrah Station'),
('213', 'Ghatakpukur', 'Babughat'),
('213/1', 'Ghatakpukur', 'Botanical Garden'),
('213A', 'Ghatakpukur', 'Narkeldanga'),
('214', 'Sajirhat', 'Esplanade'),
('214A', 'Sodepur Girja', 'Esplanade'),
('215', 'Lake Town', 'Howrah Station'),
('215/1', 'Lake Town VIP More', 'Howrah Station'),
('215A', 'Salt Lake Technopolis', 'Howrah Station'),
('215A/1', 'Salt Lake Mahishbathan', 'Howrah Station'),
('217', 'Beraberi', 'Babughat'),
('217A', 'Narayanpur', 'Babughat'),
('217B', 'Bablatala', 'Babughat'),
('218', 'Baruipur', 'Babughat'),
('219', 'Nagerbazar', 'Howrah Station'),
('219/1', 'Nagerbazar', 'Howrah Station'),
('221', 'Nagerbazar', 'Golpark'),
('222', 'Behala Chowrasta', 'Bonhooghly'),
('223', 'B.T. College', 'Golf Green'),
('227', 'B.N.R.', 'Bangur'),
('228', 'Mahamayatala', 'Babughat'),
('230', 'Kamarhati', 'Alipore'), 
('234', 'Belghoria', 'Golf Green'),
('234/1', 'Belghoria Station', 'Golf Green'),
('235', 'Amtala', 'Salt Lake Karunamoyee'),
('237', 'Tantkal', 'Babughat'),
('237/1', 'Birati', 'Babughat'),
('239', 'Salt Lake Karunamoyee', 'Babughat'),
('239B', 'Salt Lake Mahisbathan', 'Howrah Station'),
('240', 'Bagbazar', 'Jodhpur Park'),
('240/1', 'Bagbazar', 'Golf Green'),
('241', 'Santoshpur Station', 'Esplanade'),
('241A', 'Akrafatak', 'Sealdah'),
('242', 'Cossipore (4B Bus Stand)', 'Esplanade'),
('252', 'Hasnabad', 'Esplanade'),
('253', 'Basirhat', 'Esplanade'),
('257', 'Julpia', 'Kolkata Railway Station'),
('259', 'Akra', 'Howrah Station'),
('2', 'Salkia', 'Esplanade'),
('3A', 'Kamardanga', 'Esplanade'),
('5', 'Japanigate', 'Salt Lake Nicco Park'),
('6', 'Shibpur Botanical Garden', 'Esplanade'),
('6A', 'Danesh Sheikh Lane', 'Esplanade'),
('7', 'Amtala O.P.', 'Shyambazar'),
('8', 'Shibpur Tram Depot', 'Esplanade'),
('9', 'Ramrajatala', 'Rajabazar'),
('10', 'Ballykhal', 'Khiddirpur'),
('11', 'Belur Math', 'Esplanade'),
('11A', 'Diamond Park', 'Howrah Maidan'),
('KS1', 'Sarada Park (Bener Dokan)', 'Anandapur (Ruby)'),
('M8/1', 'Sonarpur Station', 'Aurobindo Setu'),
('M10', 'Diamond Harbour', 'Raidighi'),
('M13', 'Baruipur', 'Canning'),
('M14', 'Chattabazar', 'Howrah Station'),
('M15', 'Falta Sector 1', 'Bijoyganj (Lakshmikantapur)'),
('M16', 'Burul', 'Radhanagar'),
('MM3', 'Dakshineshwar', 'Duttapukur'),
('MM5', 'Barrackpore Court', 'Habra'),
('MM6', 'Jafarpur', 'Chakla'),
('MM7', 'Nabatkati', 'Dhamakhali'),
('MN2', 'Hasnabad', 'Lebukhali'),
('MN3', 'Barasat', 'Nahata'),
('MN6', 'Barasat', 'Beri Gopalpur Ghat'),
('KB12', 'Rabindra Nagar', 'Balaka Abasan'),
('KB14', 'New Barrackpore APC College Krishi Auditorium', 'Chingrighata'),
('KB16', 'Bangur', 'Sapoorji Estate'),
('KB17', 'Sonarpur Arapanch Bazar', 'Salt Lake Karunamoyee'),
('KB20', 'Jagadishpur', 'Kolkata Railway Station'),
('KB21', 'Ganganagar Julian Day School', 'Bantala Bazar'),
('DN2', 'Barasat', 'Dakshineshwar'),
('DN2/1', 'Dakshineshwar', 'Sapoorji Estate'),
('DN5', 'Barasat', 'Naihati'),
('DN8', 'Barasat Checkpost', 'Salt Lake Karunamoyee'),
('DN9', 'Barasat', 'Dakshineshwar Via Ganganagar'),
('DN9/1', 'Barasat', 'Dakshineshwar'),
('DN12', 'Bongaon', 'Basirhat'),
('DN12/1', 'Habra', 'Nazat'),
('DN16/1', 'Barasat', 'Dhamakhali/Malancha'),
('DN17', 'Barasat', 'Babughat'),
('DN18', 'Shyambazar', 'Basirhat/Baduria/Hasnabad'),
('DN21', 'Habra', 'Bagjola'),
('DN26', 'Habra', 'Jagulia'),
('DN28', 'Barasat', 'Haroa'),
('DN35', 'Barasat', 'Nabatkati'),
('DN38', 'Taranipur', 'Malancha/Basirhat'),
('DN40', 'Lauhati', 'Dakshineshwar'),
('DN42', 'Barasat', 'Dhamakhali'),
('DN43', 'Barasat Checkpost', 'Dakshineshwar'),
('DN44', 'Bongaon', 'Dakshineshwar'),
('DN46', 'Dankuni Housing Estate', 'Salt Lake Karunamoyee'),
('DN47', 'Barasat Checkpost', 'Salt Lake Karunamoyee'),
('SD3', 'Sonarpur', 'Baburhat'),
('SD4', 'Garfa', 'Thakurpukur'),
('SD4/1', 'Ruby Hospital', 'Thakurpukur'),
('SD5', 'Sonarpur', 'Khariberia'),
('SD8', 'Nandibagan', 'Bibirhat'),
('SD9', 'Esplanade', 'Noorpur via Sarisha'),
('SD9/1', 'Esplanade', 'Noorpur via Dighirpar'),
('SD11/1', 'Noorpur', 'Ramganga'),
('SD14', 'Majherhat', 'Sahararhat'),
('SD16', 'Sirakole', 'Mukundapur'),
('SD17', 'Namkhana', 'Bakkhali'),
('SD18', 'Esplanade', 'Diamond Harbour'),
('SD19', 'Esplanade', 'Patharpratima'),
('SD22', 'Esplanade', 'Sahararhat'),
('SD22/1', 'Esplanade', 'Nainan Sector 4'),
('SD24', 'Alipore Zoo', 'Basanti'),
('SD24/1', 'Alipore Zoo', 'Nazat'),
('SD26', 'Babughat', 'Burul'),
('SD27', 'Akrafatak', 'Dostipur'),
('SD28', 'New Dakghar', 'Jadavpur Central Park (Bapuji Nagar)'),
('SD29', 'Amtala', 'Baruipur'),
('SD30', 'Taratala', 'Sahararhat'),
('SD31', 'Taratala', 'Jhinki'),
('SD33', 'Baruipur', 'Jharkhali'),
('SD34', 'Canning', 'Ganga Mela'),
('SD35', 'Canning', 'Falta'),
('SD39', 'Baruipur', 'Kishorimohan'),
('SD41', 'Basanti', 'Jamtala'),
('SD50', 'Raichak', 'Patharpratima'),
('SD51', 'Gurudaspur Hospital More', 'Mathurapur Station'),
('SD53', 'Mathurapur', 'Kishorimohan'),
('SD63', 'Baruipur', 'Gadkhali'),
('SD64', 'Baruipur', 'Chunakhali Minibus'),
('SD66', 'Joka', 'Baroda Nagar (Kankondighi)'),
('SD67', 'Baruipur', 'Kaikhali'),
('SD68', 'Baruipur', 'Ghatakpukur Minibus'),
('SD69', 'Kachuberia', 'Gangasagar'),
('SD70', 'Tematha', 'Bisalakshmitala'),
('SD71', 'Thakurpukur', 'Kalicharanpur Minibus'),
('SD72', 'Baruipur', 'Noorpur'),
('SD74', 'Amtala', 'Kaikhali'),
('SD75', 'Dakshin Barasat', 'Noorpur'),
('SD76', 'Amtala', 'Ruby Hospital'),
('SD76A', 'Amtala', 'Budge Budge Station'),
('SD77', 'Joka', 'Mandirbazar'),
('SD78', 'Amtala', 'Hotore Station Minibus'),
('SD79', 'Amtala', 'Sarberia Minibus'),
('SD80', 'Kakdwip', 'Raidighi'),
('SD81', 'Budge Budge', 'Budge Budge Circular route Minibus'),
('SD82', 'Magrahat', 'Diamond Harbour Minibus'),
('K1', 'Kolkata Railway Station', 'New Town'),
('K2', 'Salt Lake 206 Bus Stand', 'Airport Gate No.1'),
('K3', 'Kudghat', 'Dakshineshwar / Rajchandrapur'),
('K4', 'Dakshineswar', 'Park Circus'),
('K6', 'Tikiapara', 'Rajabazar'),
('K7', 'Bakultala', 'Ruby Hospital'),
('K8', 'Basudebpur', 'Jadavpur Sulekha'),
('K9', 'Barrackpore Court', 'Park Circus'),
('K11', 'Domjur', 'Rabindra Sadan'),
('L2', 'Howrah Station', 'Matapara'),
('L3', 'Howrah Station', 'Jhikira'),
('L7', 'Howrah Station', 'Gadiara'),
('L238', 'Barasat', 'Howrah Station'),
('E43', 'Howrah Station', 'Dihibhursut'),
('E45', 'Howrah Station', 'Amta'),
('E53', 'Howrah Station', 'Narit'),
('007', 'Kolkata Railway Station', 'Garia Bus Stand'),
('JM1', 'Dhulagarh', 'Salt Lake Karunamoyee'),
('JM2', 'Kolkata Railway Station', 'Subhashgram Railway Station'),
('JM3', 'Ultadanga', 'Sarsuna College'),
('JM4', 'Dharsa', 'Narendrapur'),
('JM5', 'Esplanade', 'Shyampur'),
('JM8', 'Naihati', 'Salt Lake Technopolis'),
('M1', 'Unitech', 'Rashbihari'),
('M2', 'Airport', 'Rashbihari'),
('M4', 'Barasat', 'Rashbihari'),
('M5', 'Airport', 'Santragachi'),
('M20', 'Barasat', 'Exide'),
('H2', 'Ultadanga', 'Airport Gate No.1'),
('ST6', 'Tollygunge', 'Salt Lake Technopolis'),
('ST7', 'Ultadanga', 'Sapoorji Estate'),
('ST7A', 'Ultadanga', 'Hatisala'),
('ST10', 'Santragachi', 'Balaka Abasan'),
('ST11', 'Ruby Hospital', 'Balaka Abasan'),
('ST12', 'Sapoorji Estate', 'Baruipur'),
('ST13', 'Bagbazar', 'Rajarhat, Balaka Abasan'),
('V1', 'Airport', 'Tollygunge'),
('V2', 'Airport', 'Santragachi'),
('V9', 'Unitech', 'Tollygunge'),
('V10', 'Barasat', 'Chetla'),
('V13', 'Unitech', 'Chetla'),
('V20', 'Barasat', 'Exide'),
('VS1', 'Airport', 'Esplanade'),
('VS2', 'Airport', 'Howrah Station'),
('VS3', 'Parnasree', 'Airport'),
('VS4', 'Parnasree', 'Unitech'),
('VS6', 'Diamond Harbour', 'Esplanade'),
('VS8', 'Garia Bus Stand', 'Airport'),
('VS9', 'Garia Bus Stand', 'Unitech'),
('VS9A', 'Garia Bus Stand', 'Airport'),
('VS10', 'Kudghat', 'Unitech'),
('VS12', 'Santragachi', 'Salt Lake Karunamoyee'),
('MW1', 'Unitech', 'Sulekha (Jadavpur)'),
('MW2', 'Unitech', 'Howrah Station'),
('MW7', 'Bantala IT Park', 'Airport Gate No.1'),
('MW9', 'Bagbazar', 'Unitech'),
('MB1', 'Barasat', 'Santragachi'),
('MB2', 'Unitech', 'Santragachi'),
('MB3', 'Airport', 'Exide'),
('MB4', 'Barasat', 'Santragachi'),
('MB5', 'Airport', 'Santragachi'),
('MB7', 'Barasat', 'Exide'),
('MB8', 'Unitech', 'Joka'),
('MH2', 'Barasat', 'Exide'),
('MH3', 'Unitech', 'Exide'),
('MH4', 'Barasat', 'Exide'),
('NUVO2', 'Tollygunge', 'Ecospace'),
('NUVO4', 'Tollygunge', 'Airport'),
('NUVO10', 'Rashbihari', 'Barasat'),
('AC1', 'Jadavpur', 'Howrah Station'),
('AC4', 'Parnasree', 'Howrah Station'),
('AC4A', 'Parnasree', 'Sapoorji Estate'),
('AC5', 'Garia Bus Stand', 'Howrah Station'),
('AC6', 'Garia Bus Stand', 'Howrah Station'),
('AC9', 'Jadavpur', 'Salt Lake Karunamoyee'),
('AC9A', 'Golf Green', 'Dakshineshwar'),
('AC9B', 'Jadavpur', 'Ecospace'),
('AC10', 'Nilgunge', 'Howrah Station'),
('AC12', 'Sapoorji Estate', 'Howrah Station'),
('AC12D', 'Joka', 'Howrah Station'),
('AC14', 'Baruipur', 'Salt Lake Karunamoyee'),
('AC15', 'Bantala IT Park', 'Howrah Station'),
('AC17', 'Haridebpur', 'Salt lake Depot'),
('AC17B', 'Kudghat', 'Dunlop'),
('AC20', 'Barrackpore Court', 'Santragachi'),
('AC23A', 'Bally khal', 'Salt Lake Depot'),
('AC24', 'Patuli', 'Howrah Station'),
('AC25', 'New Town', 'Dunlop'),
('AC37A', 'Garia Bus Stand', 'Airport Gate No.1 (Via E.M. By­Pass)'),
('AC37B', 'Garia Bus Stand', 'Airport Gate No.1 (Via Santoshpur)'),
('AC39', 'Airport', 'Howrah Station'),
('AC41', 'Santragachi', 'Ecospace'),
('AC43', 'Golf Green', 'Airport New Terminal'),
('AC44', 'Nabanna', 'New Town'),
('AC47', 'Kudghat', 'Unitech'),
('AC48', 'Kudghat', 'Bantala IT Park'),
('AC49', 'Eden City Maheshtala', 'Airport'),
('AC49A', 'Behala no. 14 Terminus', 'Airport'),
('AC50', 'Garia', 'Belur Math'),
('AC51', 'Kudghat', 'Airport'),
('AC52', 'Amtala', 'Howrah Station'),
('AC53', 'Santragachi', 'Kasba Depot'),
('M7D', 'Kankurgachi', 'Sonamukhi Bazar'),
('M7E', 'Howrah Station', 'Bagpota'),
('Midi 1', 'Howrah', 'Rajabazar'),
('Midi 2', 'Howrah Maidan', 'Subhash Sarobar'),
('C1A', 'Sealdah', 'Danesh Shekh Lane'),
('C2A', 'Tollygunge', 'Ghatakpukur'),
('C7', 'Howrah Station', 'Harimohan Ghosh College'),
('C8', 'Barasat', 'Joka/Ruby'),
('C8A', 'Tollygunge', 'Airport Gate No.1'),
('C11', 'B.B.D. Bagh', 'Domjur'),
('C11/1', 'Howrah Station', 'Munshirhat'),
('C14/1', 'Tollygunge', 'Madhyamgram'),
('C20', 'Esplanade', 'Santragachi Station'),
('C23', 'Park Circus', 'Dankuni Housing Estate'),
('C24', 'Ghasbagan', 'Sealdah'),
('C25', 'Howrah Station', 'Salt Lake Bikash Bhawan'),
('C26', 'Howrah Station', 'Baruipur'),
('C27', 'Nabanna / Esplanade', 'Barasat University'),
('C28', 'Barrackpur', 'Howrah station'),
('C29', 'Barasat', 'Barrackpur Court'),
('C30', 'Rajabazar', 'Sankrail'),
('D1', 'Tollygunge', 'Chakdaha'),
('D2', 'Habra', 'Naihati'),
('E6', 'Esplanade', 'Amta'),
('E7', 'Esplanade', 'Bagnan'),
('E7/1', 'Esplanade', 'Shyampur'),
('E12', 'Esplanade', 'Udaynarayanpur'),
('E13', 'Esplanade', 'Jangipara'),
('E13/1', 'Esplanade', 'Jangipara'),
('E16', 'Howrah', 'Kalyani'),
('E17', 'Barasat', 'Digha'),
('E18', 'Esplanade', 'Dhamakhali'),
('E19', 'Habra', 'Digha'),
('T1', 'Dhulagarh', 'Rajabazar'),
('T2', 'B.B.D. Bagh', 'Mandirtala'),
('T3', 'Rajabazar', 'Ghatakpukur'),
('T8', 'B.B.D. Bagh', 'Tikiapara'),
('T10', 'Rajabazar', 'Chaital Ghat'),
('T10/1', 'Rajabazar', 'Bhebia'),
('T11', 'Esplanade', 'Haroa'),
('T12', 'Howrah Station', 'Chaital Ghat'),
('S­ORD­1', 'Howrah Station', 'Amtala'),
('S­ORD­2', 'Howrah Station', 'Joka'),
('NB1', 'Sealdah', 'Nabanna'),
('NB2', 'B.B.D. Bagh', 'Nabanna');
select * from bus;